project_id = "zcsnqvncqzpleqoctzfc"

[functions.seed-test-users]
verify_jwt = false

[functions.generate-section-quizzes]
verify_jwt = false

[functions.moderate-photo]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false
